import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { StockProvider } from "./context/StockContext";
import Head from "next/head";
import { Providers } from "./providers";

const geistSans = localFont({
   src: "./fonts/GeistVF.woff",
   variable: "--font-geist-sans",
   weight: "100 900",
});
const geistMono = localFont({
   src: "./fonts/GeistMonoVF.woff",
   variable: "--font-geist-mono",
   weight: "100 900",
});

export const metadata: Metadata = {
   title: "Stockfolio",
   description: "Generated by create next app",
   icons: {
      icon: [{ url: "/favicon.ico" }, { url: "/favicon.png", type: "image/png" }],
   },
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <head>
            <link
               rel="stylesheet"
               href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
               integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
               crossOrigin="anonymous"
               referrerPolicy="no-referrer"
            />
         </head>
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Providers>{children}</Providers>
         </body>
      </html>
   );
}
